name: CI

on:
  push:
    branches-ignore:
      - 'gh-pages'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get branch name
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Check if default branch
        run: |
          DEFAULT_BRANCH=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')
          if [ "$BRANCH_NAME" == "$DEFAULT_BRANCH" ]; then
            echo "IS_DEFAULT_BRANCH=true" >> $GITHUB_ENV
          else
            echo "IS_DEFAULT_BRANCH=false" >> $GITHUB_ENV
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install SUSHI
        run: npm install -g fsh-sushi

      - name: Render decision tables from DMN
        run: python3 render-decision-tables.py

      - name: Run SUSHI
        run: sushi .

      - name: Download IG Publisher
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: curl -L https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -o ./input-cache/publisher.jar --create-dirs

      - name: Create package cache folder
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          entrypoint: /bin/sh
          args: -c "mkdir -p ./fhir-package-cache && chown 1001:127 ./fhir-package-cache"

      - name: Install Python in Docker and run IG Publisher
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          entrypoint: /bin/sh
          args: -c "apt-get update -qq && apt-get install -y -qq python3 > /dev/null 2>&1 && ln -sf $(which python3) /usr/local/bin/python && java -Xmx6g -jar ./input-cache/publisher.jar publisher -ig . -auto-ig-build -repo https://github.com/${{github.repository}}/tree/${{github.ref_name}} -package-cache-folder ./fhir-package-cache"

      - name: Upload qa.json artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: qa-json-artifact
          path: ./output/qa.json

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v7.0.7

      - name: Deploy candidate branch
        uses: JamesIves/github-pages-deploy-action@v4.6.8
        if: env.IS_DEFAULT_BRANCH == 'false'
        with:
          branch: gh-pages
          folder: ./output
          commit-message: Deploy candidate branch
          target-folder: branches/${{ steps.branch-name.outputs.current_branch }}
          single-commit: true
          clean: false

      - name: Deploy main
        uses: JamesIves/github-pages-deploy-action@v4.6.8
        if: env.IS_DEFAULT_BRANCH == 'true'
        with:
          branch: gh-pages
          folder: ./output
          commit-message: Deploy main branch
          single-commit: true
          clean-exclude: |
            branches
            sitepreview
